# Generated by Django 4.0.4 on 2022-05-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='ایمیل کاربر')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='نام کاربری')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن کاربر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مجوز ورود به سایت؟')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین سایت؟')),
                ('is_author', models.BooleanField(default=False, verbose_name='نویسنده سایت؟')),
                ('email_activate', models.BooleanField(default=False, verbose_name=' ایا ایمیل فعال شده ؟')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
