# Generated by Django 4.0.4 on 2022-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره تماس')),
                ('code', models.PositiveSmallIntegerField(verbose_name='رمز یکبار مصرف')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد شده')),
            ],
        ),
    ]
