version: '3.4'

services:

  postgres:
    container_name: postgres
    image: postgres:13.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lorazpam
      - POSTGRES_DB=shop
    networks:
      - main
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: sh -c "python manage.py migrate && gunicorn shop.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - main
    restart: on-failure

  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  main:

volumes:
  postgres_data: