# Generated by Django 4.0.4 on 2022-05-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_color_ipaddress_size_variant_product_visit_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'تنوع', 'verbose_name_plural': 'تنوع ها'},
        ),
        migrations.AddField(
            model_name='variant',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رنگ'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=100, verbose_name='نام رنگ'),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=100, verbose_name='نام سایز'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_color', to='product.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='discount',
            field=models.IntegerField(verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_product', to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='sell',
            field=models.IntegerField(default=0, verbose_name='فروش'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_size', to='product.size', verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='title',
            field=models.CharField(max_length=200, verbose_name='نام تنوع'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='قیمت اصلی(تخفیف خورده)'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='وزن'),
        ),
    ]
