# Generated by Django 4.0.4 on 2022-05-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_comment_post_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
