# Generated by Django 4.0.4 on 2022-06-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_variant_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ ها'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'سایز', 'verbose_name_plural': 'سایز ها'},
        ),
    ]
